import { Ionicons } from '@expo/vector-icons';
import * as Haptics from 'expo-haptics'; import { useKeepAwake } from 'expo-keep-awake'; import * as Linking from 'expo-linking';
import { router } from 'expo-router'; import { useMemo, useRef, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native'; import { SafeAreaView } from 'react-native-safe-area-context';
import { PrimaryButton } from '@/components/PrimaryButton'; import { colors } from '@/constants/theme'; import { useAppData } from '@/context/AppDataContext'; import { getLevel } from '@/domain/exercises'; import { snapshotExercise, WorkoutSession } from '@/domain/types';
export default function WorkoutSessionScreen(){
  useKeepAwake(); const {profile,addSession}=useAppData(); const level=useMemo(()=>getLevel(profile.currentLevel),[profile.currentLevel]);
  const startedAt=useRef(new Date().toISOString()); const [index,setIndex]=useState(0); const [counts,setCounts]=useState(()=>level.exercises.map(()=>0)); const [setTimes,setSetTimes]=useState(()=>level.exercises.map(()=>[] as string[])); const [saving,setSaving]=useState(false); const savingRef=useRef(false); const exercise=level.exercises[index];
  const completeWorkout=async(nextCounts:number[],nextTimes:string[][])=>{if(savingRef.current)return;savingRef.current=true;setSaving(true);const session:WorkoutSession={schemaVersion:2,id:`${Date.now()}-${Math.random().toString(36).slice(2,8)}`,startedAt:startedAt.current,completedAt:new Date().toISOString(),level:level.level,levelName:level.name,exercises:level.exercises.map((e,i)=>({exercise:snapshotExercise(e),sets:nextTimes[i].slice(0,nextCounts[i]).map((completedAt)=>({completedAt,measurements:{}}))})),fullyCompleted:level.exercises.every((e,i)=>nextCounts[i]===e.totalSets)};try{await addSession(session);router.replace({pathname:'/workout/complete',params:{id:session.id}})}catch{savingRef.current=false;setSaving(false);Alert.alert('저장하지 못했습니다','잠시 후 다시 시도해 주세요.')}};
  const completeSet=async()=>{if(savingRef.current||counts[index]>=exercise.totalSets)return;await Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);const next=[...counts];next[index]+=1;const nextTimes=setTimes.map((times,i)=>i===index?[...times,new Date().toISOString()]:times);setCounts(next);setSetTimes(nextTimes);if(next[index]===exercise.totalSets){if(index===level.exercises.length-1){await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);await completeWorkout(next,nextTimes)}else{setTimeout(()=>setIndex(i=>Math.min(i+1,level.exercises.length-1)),450)}}};
  const progress=(index/level.exercises.length)*100; return <SafeAreaView style={styles.safe} edges={['bottom']}><View style={styles.progressTrack}><View style={[styles.progressFill,{width:`${progress}%`}]} /></View><ScrollView contentContainerStyle={styles.content}>
    <Text style={styles.order}>{index+1} / {level.exercises.length}</Text><Text style={styles.name}>{exercise.name}</Text><Text style={styles.purpose}>{exercise.purpose}</Text>
    <View style={styles.target}><Text style={styles.label}>목표</Text><Text style={styles.targetText}>{exercise.targetText}</Text><Text style={styles.setTotal}>총 {exercise.totalSets}세트</Text></View>
    <View style={styles.sets}>{Array.from({length:exercise.totalSets},(_,i)=>{const done=i<counts[index];const active=i===counts[index];return <View key={i} style={styles.setRow}><View style={[styles.check,done&&styles.checkDone]}>{done&&<Ionicons name="checkmark" size={20} color="#FFF"/>}</View><Text style={[styles.setText,done&&styles.doneText]}>{i+1}세트</Text><Text style={[styles.setStatus,active&&styles.activeStatus]}>{done?'완료':active?'시작':'대기'}</Text></View>})}</View>
    <View style={styles.caution}><Ionicons name="alert-circle-outline" size={22} color={colors.warningText}/><Text style={styles.cautionText}>{exercise.caution}</Text></View>
    <View style={styles.instructions}>{exercise.instructions.map((item,i)=><View key={item} style={styles.instruction}><Text style={styles.bullet}>{i+1}</Text><Text style={styles.instructionText}>{item}</Text></View>)}</View>
    {exercise.videoUrl&&<Pressable style={styles.video} onPress={()=>Linking.openURL(exercise.videoUrl!)}><Ionicons name="logo-youtube" size={22} color="#D92D20"/><Text style={styles.videoText}>레퍼런스 영상 보기</Text><Ionicons name="open-outline" size={18} color={colors.muted}/></Pressable>}
  </ScrollView><View style={styles.controls}><PrimaryButton title={saving?'저장 중...':'세트 완료'} loading={saving} disabled={counts[index]>=exercise.totalSets} onPress={completeSet}/><View style={styles.nav}><Pressable disabled={index===0} style={[styles.navButton,index===0&&styles.disabled]} onPress={()=>setIndex(i=>i-1)}><Ionicons name="chevron-back" size={20}/><Text>이전 운동</Text></Pressable><Pressable disabled={index===level.exercises.length-1} style={[styles.navButton,index===level.exercises.length-1&&styles.disabled]} onPress={()=>setIndex(i=>i+1)}><Text>다음 운동</Text><Ionicons name="chevron-forward" size={20}/></Pressable></View><Text style={styles.safety}>손가락·손목·목·어깨의 날카로운 통증, 저림 또는 힘 빠짐이 나타나면 운동을 중단하세요.</Text></View></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:colors.background},progressTrack:{height:5,backgroundColor:colors.border},progressFill:{height:5,backgroundColor:colors.primary},content:{padding:20,paddingBottom:24},order:{fontSize:15,fontWeight:'800',color:colors.primary,marginTop:4},name:{fontSize:32,fontWeight:'800',color:colors.text,marginTop:10},purpose:{fontSize:15,lineHeight:22,color:colors.muted,marginTop:8},target:{marginTop:22,paddingVertical:18,borderTopWidth:1,borderBottomWidth:1,borderColor:colors.border},label:{fontSize:13,fontWeight:'700',color:colors.muted},targetText:{fontSize:24,fontWeight:'800',color:colors.text,marginTop:5},setTotal:{fontSize:15,color:colors.muted,marginTop:5},sets:{paddingVertical:12},setRow:{height:52,flexDirection:'row',alignItems:'center',gap:12},check:{width:30,height:30,borderRadius:15,borderWidth:2,borderColor:colors.border,alignItems:'center',justifyContent:'center'},checkDone:{backgroundColor:colors.primary,borderColor:colors.primary},setText:{fontSize:17,fontWeight:'700',color:colors.text},doneText:{color:colors.muted},setStatus:{marginLeft:'auto',fontSize:14,color:colors.muted,fontWeight:'600'},activeStatus:{color:colors.primary},caution:{flexDirection:'row',gap:10,backgroundColor:colors.warning,padding:14,borderRadius:8,alignItems:'center'},cautionText:{flex:1,fontSize:15,lineHeight:21,fontWeight:'700',color:colors.warningText},instructions:{marginTop:18,gap:12},instruction:{flexDirection:'row',gap:10},bullet:{width:24,height:24,borderRadius:12,textAlign:'center',textAlignVertical:'center',backgroundColor:colors.accent,color:colors.primary,fontWeight:'700'},instructionText:{flex:1,fontSize:15,lineHeight:22,color:colors.text},video:{minHeight:50,flexDirection:'row',alignItems:'center',gap:10,marginTop:18,paddingHorizontal:14,borderWidth:1,borderColor:colors.border,borderRadius:8,backgroundColor:colors.surface},videoText:{flex:1,fontSize:15,fontWeight:'700',color:colors.text},controls:{padding:16,paddingBottom:10,backgroundColor:colors.surface,borderTopWidth:1,borderColor:colors.border},nav:{flexDirection:'row',justifyContent:'space-between',marginTop:8},navButton:{minHeight:44,flexDirection:'row',alignItems:'center',gap:3,paddingHorizontal:5},disabled:{opacity:.25},safety:{fontSize:11,lineHeight:16,textAlign:'center',color:colors.muted,marginTop:5}});
