import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import { Screen } from '@/components/Screen'; import { PrimaryButton } from '@/components/PrimaryButton';
import { colors } from '@/constants/theme'; import { useAppData } from '@/context/AppDataContext'; import { getLevel } from '@/domain/exercises';
import { countThisWeek, formatKoreanDate, isToday } from '@/utils/date';
export default function HomeScreen() {
  const { profile, sessions, loading } = useAppData(); const level = getLevel(profile.currentLevel);
  const todayDone = sessions.some((s) => isToday(s.completedAt)); const recent = sessions[0]; const weekly = countThisWeek(sessions);
  if (loading) return <View style={styles.loading}><ActivityIndicator color={colors.primary} size="large" /></View>;
  return <Screen><View style={styles.top}><View><Text style={styles.hello}>안녕하세요,</Text><Text style={styles.name}>{profile.name}님</Text></View><Pressable accessibilityLabel="설정" hitSlop={10} style={styles.iconButton} onPress={() => router.push('/settings')}><Ionicons name="settings-outline" size={25} color={colors.text} /></Pressable></View>
    <View style={styles.levelBand}><Text style={styles.overline}>현재 단계</Text><Text style={styles.level}>Level {level.level} · {level.name}</Text><Text style={styles.summary}>{level.summary}</Text></View>
    <View style={styles.weekRow}><View><Text style={styles.overline}>이번 주 운동</Text><Text style={styles.count}>{weekly} <Text style={styles.countSmall}>/ {profile.weeklyTarget}회</Text></Text></View><View style={[styles.status, todayDone && styles.statusDone]}><Ionicons name={todayDone ? 'checkmark-circle' : 'ellipse-outline'} size={20} color={todayDone ? colors.primary : colors.muted} /><Text style={styles.statusText}>{todayDone ? '오늘 완료' : '오늘 미완료'}</Text></View></View>
    <View style={styles.action}><Text style={styles.actionTitle}>{todayDone ? '오늘 운동 완료' : '10분 루틴을 시작하세요'}</Text><Text style={styles.actionCopy}>{todayDone ? '같은 날 다시 운동해도 기록할 수 있습니다.' : '각 세트를 마친 뒤 완료만 누르면 됩니다.'}</Text><PrimaryButton title={todayDone ? '한 번 더 운동하기' : '오늘 운동 시작'} onPress={() => router.push('/workout/session')} /></View>
    <View style={styles.infoRow}><View><Text style={styles.overline}>최근 운동</Text><Text style={styles.info}>{recent ? formatKoreanDate(recent.completedAt) : '아직 기록이 없습니다'}</Text></View></View>
    <View style={styles.goal}><Ionicons name="flag-outline" size={22} color={colors.primary} /><View><Text style={styles.overline}>장기 목표</Text><Text style={styles.info}>{profile.longTermGoal}</Text></View></View>
    {sessions.filter((s) => s.fullyCompleted && s.level === 1).length >= 6 && <Text style={styles.suggestion}>현재 루틴이 편해졌다면 다음 단계로 변경해보세요.</Text>}
  </Screen>;
}
const styles = StyleSheet.create({ loading:{flex:1,alignItems:'center',justifyContent:'center',backgroundColor:colors.background}, top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:28}, hello:{fontSize:16,color:colors.muted},name:{fontSize:28,fontWeight:'800',color:colors.text},iconButton:{width:48,height:48,borderRadius:8,alignItems:'center',justifyContent:'center',backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border},levelBand:{backgroundColor:colors.accent,padding:20,borderRadius:8,marginBottom:18},overline:{fontSize:13,color:colors.muted,fontWeight:'600',marginBottom:5},level:{fontSize:22,fontWeight:'800',color:colors.primaryDark},summary:{fontSize:15,color:colors.muted,marginTop:7},weekRow:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border,borderRadius:8,padding:20,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},count:{fontSize:28,fontWeight:'800',color:colors.text},countSmall:{fontSize:17,color:colors.muted},status:{flexDirection:'row',gap:6,alignItems:'center',backgroundColor:colors.background,padding:10,borderRadius:8},statusDone:{backgroundColor:colors.accent},statusText:{fontSize:14,fontWeight:'700',color:colors.text},action:{marginVertical:24,gap:10},actionTitle:{fontSize:23,fontWeight:'800',color:colors.text},actionCopy:{fontSize:15,color:colors.muted,marginBottom:8},infoRow:{paddingVertical:18,borderTopWidth:1,borderColor:colors.border},info:{fontSize:17,fontWeight:'700',color:colors.text},goal:{flexDirection:'row',gap:12,alignItems:'center',paddingVertical:18,borderTopWidth:1,borderColor:colors.border},suggestion:{marginTop:8,padding:14,backgroundColor:colors.warning,color:colors.warningText,borderRadius:8,fontWeight:'600'} });
